<?php

namespace AppBundle\Repository;

/**
 * DalykasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DalykasRepository extends \Doctrine\ORM\EntityRepository
{
}
