<?php

namespace AppBundle\Repository;

/**
 * ProgramaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgramRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProgramFields()
    {
        $qb = $this->getEntityManager();
        $queryFields = $qb->createQuery(
            'SELECT DISTINCT p.field
            FROM AppBundle:Program p
            ORDER by p.field ASC'
        );
        return $queryFields->getArrayResult();
    }
}
