app.index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
doctrine.add:
    path:     /Doctrine/Add/{dalykas}
    defaults: { _controller: AppBundle:Doctrine:add }
doctrine.view:
        path:     /Doctrine/View
        defaults: { _controller: AppBundle:Doctrine:view }
doctrine.view.id:
        path:     /Doctrine/View/{id}
        defaults: { _controller: AppBundle:Doctrine:viewId }
doctrine.delete.id:
        path:     /Doctrine/Delete/{id}
        defaults: { _controller: AppBundle:Doctrine:delete }
doctrine.update.id:
        path:     /Doctrine/Update/{id}
        defaults: { _controller: AppBundle:Doctrine:update }
